image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      chmod +x envconfig.sh &&
      ./envconfig.sh
  - command: >
      export CMAKE_PREFIX=/opt/conda

vscode:
  extensions:
    - ms-vscode.cpptools@0.26.2:Pq/tmf2WN3SanVzB4xZc1g==
    - ms-vscode.cmake-tools@1.4.2:85XiRZZTNCh6JgvEqefqww==