language: cpp
dist: trusty
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - catch
      env: COMPILER=gcc GCC=7 BLAS=OpenBLAS BUILD_TYPE='Debug'
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - catch
      env: COMPILER=gcc GCC=7 BLAS=OpenBLAS BUILD_TYPE='Release'
env:
  global:
    - MINCONDA_VERSION="latest"
    - MINCONDA_LINUX="Linux-x86_64"
    - MINCONDA_OSX="MacOSX-x86_64"
before_install:
    - |
      # Configure build variables
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        if [[ "$COMPILER" == "gcc" ]]; then
          export CXX=g++-$GCC CC=gcc-$GCC;
        fi
        if [[ "$COMPILER" == "clang" ]]; then
          export CXX=clang++-$CLANG CC=clang-$CLANG;
        fi
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export CXX=clang++ CC=clang;
      fi
install:
    # Define the version of miniconda to download
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        MINCONDA_OS=$MINCONDA_LINUX;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        MINCONDA_OS=$MINCONDA_OSX;
      fi
    - wget "http://repo.continuum.io/miniconda/Miniconda3-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh;
    - export CONDA_PREFIX=$HOME/miniconda
    - bash miniconda.sh -b -p $CONDA_PREFIX
    - export PATH="$CONDA_PREFIX/bin:$PATH"
    - export LD_LIBRARY_PATH="$CONDA_PREFIX/lib"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    # - conda install gtest cmake -c conda-forge
    # Install xtensor and BLAS
    - conda install xtensor=0.15.6 -c conda-forge
    # - conda install xtensor -c conda-forge
    - conda install xtensor-blas -c conda-forge
    - if [[ "$BLAS" == "OpenBLAS" ]]; then
        conda install openblas -c conda-forge;
      elif [[ "$BLAS" == "mkl" ]]; then
        conda install mkl;
      fi
    - conda install lapack -c conda-forge
    - conda install libboost -c conda-forge
    # Testing
    - if [[ "$BOUND_CHECKS" == 1 ]]; then
        cmake -DXTENSOR_ENABLE_ASSERT=ON -DBUILD_TESTS=ON -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DCMAKE_BUILD_TYPE=${BUILD_TYPE}-DCMAKE_SYSTEM_IGNORE_PATH=/usr/lib .;
      else
        cmake -DBUILD_TESTS=ON -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DCMAKE_BUILD_TYPE=${BUILD_TYPE}-DCMAKE_SYSTEM_IGNORE_PATH=/usr/lib .;
      fi
    - make -j2
script:
    - ctest -V -j 2
notifications:
  email: false
  slack:
    rooms:
      - loksu:jErzuILLSNn9qGYkkILvBwje#netoptimcpp
